# Generated by Django 4.2.2 on 2023-06-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impressions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('address', django_google_maps.fields.AddressField(max_length=255, verbose_name='Адрес')),
                ('location', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='ГеоЛокация')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Впечатление',
                'verbose_name_plural': 'Впечатления',
                'ordering': ['-created'],
            },
        ),
    ]
