# Generated by Django 4.2.2 on 2023-06-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressions', '0002_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
